# espanso configuration file
# --- Toggle key
search_trigger: ".search"
search_shortcut: off

# Enable/disable the config auto-reload after a file change is detected.
auto_restart: true

# Explicitly set keyboard layout to have unicode characters
# Espanso cannot auto-detect the layout under Wayland/EVDEV
# LAPTOP: Add this to use colemak_dh 
#  keyboard_layout:
#  layout: "us"
#  variant: "colemak_dh"
#  options: "compose:caps"
keyboard_layout:
  layout: "us"
  variant: "altgr-intl"
  options: "compose:caps"

# TO FIX /dev/input PERMISSIONS
#    By default, input devices are owned root:root.
#    Create a udev rule to allow the "input" group to read them:
#
#      echo 'SUBSYSTEM=="input", GROUP:="input", MODE:="0660"' \
#        | sudo tee /etc/udev/rules.d/99-input.rules
#
#      sudo udevadm control --reload-rules
#      sudo udevadm trigger --action=add   # <-- must be "add", not default "change"
#
# INSTALL EVTEST to verify
# sudo evtest
# sudo pacman -S evtest

